# Generated by Django 6.0.3 on 2026-03-21 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.shop')),
            ],
        ),
    ]
