# Generated by Django 6.0.3 on 2026-03-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_country_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sell',
            field=models.BooleanField(default=False),
        ),
    ]
